### ISSUE TITLE
为了安全开启了家父手机的云服务，结果短信费花了100多

### ISSUE THREAD

**Issue by maybeloveu** [fineemb/xiaomi-cloud#5]
父母的手机经常不开移动网络，后来查话费多了100多一查都是短信，可能使用了短信返回定位信息，希望能能判断是否使用移动网络，若使用移动网络再查询位置。

**Comment by Marsmz** [comment]
+1 没有你的扣的多，但是也多扣了好几十块钱

**Comment by fineemb** [comment]
修改增加默认扫描间隔时间, 目前只能这样.
